services:
  web:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo  # Guarda los datos de Odoo
      - ./addons:/mnt/extra-addons # Carpeta para los módulos personalizados
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: ["--dev=all", "--log-level=debug"]  # Agregar para desarrollo

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data # Guarda los datos de la base de datos
    ports:
      - "5432:5432"  # Opcional: para acceso directo a la DB

volumes:
  pg_data:
  odoo-web-data: